package simx.components.renderer.gui.ontology.functions

/**
 * This file is automatically generated from an ontology.
 * DO NOT EDIT!
 */

import simx.core.entity.description.Interpolator

trait Interpolators {
	implicit val guiInterpolator: Interpolator[simx.core.svaractor.SVarActor.Ref,simx.core.ontology.Symbols.gui.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val isdraggableInterpolator: Interpolator[scala.Boolean,simx.core.ontology.Symbols.isDraggable.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val iselasticInterpolator: Interpolator[scala.Boolean,simx.core.ontology.Symbols.isElastic.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val islootInterpolator: Interpolator[scala.Boolean,simx.core.ontology.Symbols.isLoot.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val layerInterpolator: Interpolator[scala.Int,simx.core.ontology.Symbols.layer.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val notificationlinearoffsetInterpolator: Interpolator[scala.Float,simx.core.ontology.Symbols.notificationLinearOffset.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val notificationlinearvelocityInterpolator: Interpolator[scala.Boolean,simx.core.ontology.Symbols.notificationLinearVelocity.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val posxInterpolator: Interpolator[scala.Float,simx.core.ontology.Symbols.posX.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val posyInterpolator: Interpolator[scala.Float,simx.core.ontology.Symbols.posY.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val shadercolorInterpolator: Interpolator[simplex3d.math.floatx.ConstVec4f,simx.core.ontology.Symbols.shaderColor.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val shaderdurationinsecInterpolator: Interpolator[scala.Float,simx.core.ontology.Symbols.shaderDurationInSec.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val shaderradiusinmeterInterpolator: Interpolator[scala.Float,simx.core.ontology.Symbols.shaderRadiusInMeter.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val shapeInterpolator: Interpolator[simx.components.renderer.gui.Shape,simx.core.ontology.Symbols.shape.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
	implicit val tangiblelistInterpolator: Interpolator[scala.List[scala.Symbol],simx.core.ontology.Symbols.tangibleList.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
}